version: '3.8'

services:
  web:
    build: .
    container_name: ebast-web-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=ebast.settings
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:13
    container_name: ebast-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ebast_dev
      - POSTGRES_USER=ebast
      - POSTGRES_PASSWORD=ebast_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ebast -d ebast_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:

networks:
  default:
    name: ebast_dev_network