services:
  web:
    build: .
    container_name: ebast-image
    command: gunicorn ebast.wsgi:application
    ports:
      - "127.0.0.1:8080:8000"
    volumes:
      - ./ebast:/app
    restart: always
    environment:
      - DEBUG=False

networks:
  default:
    external: true
    name: proxy_network
