version: '3.8'

services:
  web:
    build: .
    container_name: ebast-test
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ebast.settings
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s