# Generated by Django 5.1.3 on 2024-12-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Petugas',
            new_name='Operator',
        ),
    ]
