# Generated by Django 5.1.3 on 2025-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_petugas_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
