# Generated by Django 5.1.3 on 2025-02-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kelompok_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='name',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
    ]
