# Generated by Django 5.1.3 on 2025-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_kelompok_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelompok',
            name='member',
        ),
        migrations.AddField(
            model_name='kelompok',
            name='member',
            field=models.CharField(default='', max_length=300),
        ),
    ]
