# Generated by Django 5.1.3 on 2024-12-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_id', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StationListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('digitizer_type', models.CharField(max_length=100)),
                ('UPT', models.CharField(max_length=50)),
            ],
        ),
    ]
