# Generated by Django 5.1.3 on 2024-12-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0001_initial'),
        ('core', '0002_rename_petugas_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_id', models.CharField(default='0', max_length=15)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='P', max_length=15)),
                ('jam_pelaksanaan', models.CharField(choices=[('00:00 WIB', '00:00 WIB'), ('06:00 WIB', '06:00 WIB'), ('12:00 WIB', '12:00 WIB'), ('18:00 WIB', '18:00 WIB')], default='12:00 WIB', max_length=20)),
                ('kelompok', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('gaps', models.TextField(blank=True, max_length=10000, null=True)),
                ('spikes', models.TextField(blank=True, max_length=10000, null=True)),
                ('blanks', models.TextField(blank=True, max_length=10000, null=True)),
                ('slmon', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_gaps', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_spikes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('count_blanks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
        migrations.DeleteModel(
            name='CsRecord',
        ),
    ]
