# Generated by Django 5.1.3 on 2024-12-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0002_csrecordmodel_delete_csrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrecordmodel',
            name='slmon_image',
            field=models.ImageField(blank=True, null=True, upload_to='slmon_images/'),
        ),
    ]
