# Generated by Django 5.1.3 on 2024-12-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0003_csrecordmodel_slmon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrecordmodel',
            name='slmon_image',
            field=models.ImageField(blank=True, null=True, upload_to='cl_seiscomp/slmon_images/'),
        ),
    ]
