# Generated by Django 5.1.3 on 2025-01-14 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0004_alter_csrecordmodel_slmon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrecordmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
