# Generated by Django 5.1.2 on 2025-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_seiscomp', '0005_csrecordmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrecordmodel',
            name='kelompok',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
