# Generated by Django 4.0.6 on 2023-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gaps', models.JSONField(null=True)),
                ('spikes', models.JSONField(null=True)),
                ('blanks', models.JSONField(null=True)),
                ('operator', models.CharField(max_length=100)),
                ('group', models.IntegerField()),
                ('time', models.IntegerField()),
                ('gaps_count', models.IntegerField()),
                ('spikes_count', models.IntegerField()),
                ('blanks_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
