# Generated by Django 4.0.6 on 2023-02-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistSModel',
            new_name='ChecklistSeiscompModel',
        ),
    ]
