# Generated by Django 4.0.6 on 2023-03-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0005_alter_checklistseiscompmodel_blanks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='blanks_count',
        ),
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='gaps_count',
        ),
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='spikes_count',
        ),
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='total_count',
        ),
    ]
