# Generated by Django 4.0.6 on 2023-03-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0007_alter_checklistseiscompmodel_blanks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='date',
        ),
    ]
