# Generated by Django 4.0.6 on 2023-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0008_remove_checklistseiscompmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistseiscompmodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
