# Generated by Django 4.0.6 on 2023-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0009_remove_checklistseiscompmodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
