# Generated by Django 4.0.6 on 2023-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0015_alter_checklistseiscompmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
    ]
