# Generated by Django 4.0.6 on 2023-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0016_alter_checklistseiscompmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
