# Generated by Django 4.0.6 on 2023-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0017_alter_checklistseiscompmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='group',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
