# Generated by Django 4.0.6 on 2023-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0018_checklistseiscompmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
