# Generated by Django 4.0.6 on 2023-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0019_alter_checklistseiscompmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
