# Generated by Django 4.0.6 on 2023-03-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0023_alter_checklistseiscompmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistseiscompmodel',
            old_name='time',
            new_name='jam',
        ),
        migrations.RenameField(
            model_name='checklistseiscompmodel',
            old_name='group',
            new_name='kelompok',
        ),
        migrations.RenameField(
            model_name='checklistseiscompmodel',
            old_name='date',
            new_name='tanggal',
        ),
    ]
