# Generated by Django 4.0.6 on 2023-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0024_rename_time_checklistseiscompmodel_jam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='blanks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='gaps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='spikes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
