# Generated by Django 4.0.6 on 2023-03-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0025_alter_checklistseiscompmodel_blanks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistseiscompmodel',
            old_name='kelompok',
            new_name='group',
        ),
    ]
