# Generated by Django 4.0.6 on 2023-03-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0026_rename_kelompok_checklistseiscompmodel_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistseiscompmodel',
            old_name='group',
            new_name='kelompok',
        ),
    ]
