# Generated by Django 4.0.6 on 2023-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0027_rename_group_checklistseiscompmodel_kelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='jam',
            field=models.CharField(choices=[('12:00 WIB', '12:00 WIB'), ('00:00 WIB', '00:00 WIB')], default='12:00 WIB', max_length=20),
        ),
    ]
