# Generated by Django 4.0.6 on 2023-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0028_alter_checklistseiscompmodel_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='operator',
            field=models.TextField(null=True),
        ),
    ]
