# Generated by Django 4.0.6 on 2023-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0029_alter_checklistseiscompmodel_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='kelompok',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
