# Generated by Django 4.0.6 on 2023-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0032_alter_checklistseiscompmodel_kelompok'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='slmon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
