# Generated by Django 4.0.6 on 2023-03-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0034_alter_checklistseiscompmodel_slmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='slmon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
