# Generated by Django 4.0.6 on 2023-03-31 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0036_alter_checklistseiscompmodel_slmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='slmon',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
