# Generated by Django 4.0.6 on 2023-04-02 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0038_alter_checklistseiscompmodel_slmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='slmon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
