# Generated by Django 4.0.6 on 2023-04-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0039_alter_checklistseiscompmodel_slmon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='tanggal',
            field=models.TextField(null=True),
        ),
    ]
