# Generated by Django 4.0.6 on 2023-04-02 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0040_alter_checklistseiscompmodel_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
