# Generated by Django 4.0.6 on 2023-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0041_alter_checklistseiscompmodel_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='tanggal',
            field=models.TextField(null=True),
        ),
    ]
