# Generated by Django 4.1.7 on 2023-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0043_alter_checklistseiscompmodel_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('stasiun', models.CharField(max_length=200)),
                ('tipe', models.CharField(max_length=50)),
            ],
        ),
    ]
