# Generated by Django 4.2.4 on 2023-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0045_rename_stasiun_stationlistmodel_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistseiscompmodel',
            name='jam',
            field=models.CharField(choices=[('12:00 WIB', '12:00 WIB'), ('18:00 WIB', '18:00 WIB'), ('00:00 WIB', '00:00 WIB')], default='12:00 WIB', max_length=20),
        ),
    ]
