# Generated by Django 4.2.4 on 2023-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0050_alter_checklistseiscompmodel_blanks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatormodel',
            name='nip',
            field=models.IntegerField(default=0, max_length=18),
        ),
    ]
