# Generated by Django 4.2.4 on 2023-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0051_operatormodel_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatormodel',
            name='nip',
            field=models.CharField(max_length=18),
        ),
    ]
