# Generated by Django 4.2.4 on 2023-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0052_alter_operatormodel_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='shift',
            field=models.TextField(null=True),
        ),
    ]
