# Generated by Django 4.2.4 on 2023-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChecklistSeiscomp', '0057_remove_checklistseiscompmodel_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='count_blanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='count_gaps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistseiscompmodel',
            name='count_spikes',
            field=models.IntegerField(default=0),
        ),
    ]
