# Generated by Django 5.1.3 on 2024-12-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_alter_qcrecord_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('NIP', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Operators',
            },
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='NIP',
            field=models.CharField(default='000000', max_length=100),
        ),
    ]
