# Generated by Django 5.1.3 on 2024-12-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0005_alter_qcrecord_nip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qcrecord',
            table=None,
        ),
    ]
