# Generated by Django 5.1.3 on 2024-12-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_qcrecord_qc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcrecord',
            name='date_created',
        ),
    ]
