# Generated by Django 5.1.3 on 2024-12-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_remove_qcrecord_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='qc_id',
            field=models.TextField(),
        ),
    ]
