# Generated by Django 5.1.3 on 2024-12-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0011_alter_qcrecord_qc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='date',
            field=models.DateTimeField(default='2024-12-12 00:00:00'),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='qc_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
