# Generated by Django 5.1.3 on 2024-12-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0013_remove_qcrecord_date_alter_qcrecord_qc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='kelompok',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
