# Generated by Django 5.1.3 on 2024-12-14 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0025_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 11, 55, tzinfo=datetime.timezone.utc)),
        ),
    ]
