# Generated by Django 5.1.3 on 2024-12-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0031_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
        ),
    ]
