# Generated by Django 5.1.3 on 2024-12-18 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0034_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcrecord',
            name='kelompok',
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 10, 39, tzinfo=datetime.timezone.utc)),
        ),
    ]
