# Generated by Django 5.1.3 on 2024-12-18 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0035_remove_qcrecord_kelompok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='kelompok',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 10, 40, tzinfo=datetime.timezone.utc)),
        ),
    ]
