# Generated by Django 5.1.3 on 2024-12-19 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0036_qcrecord_kelompok_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 20, 4, 13, tzinfo=datetime.timezone.utc)),
        ),
    ]
