# Generated by Django 5.1.3 on 2024-12-20 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0038_alter_qcrecord_nip_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='event_indonesia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='event_luar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='NIP',
            field=models.CharField(default='0', max_length=18),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 20, 8, 2, tzinfo=datetime.timezone.utc)),
        ),
    ]
