# Generated by Django 5.1.3 on 2024-12-24 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_petugas_operator'),
        ('qc', '0043_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator'),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 24, 23, 55, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='operator',
        ),
    ]
