# Generated by Django 5.1.3 on 2024-12-24 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0044_alter_qcrecord_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 24, 23, 56, tzinfo=datetime.timezone.utc)),
        ),
    ]
