# Generated by Django 5.1.3 on 2024-12-28 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0048_alter_qcrecord_jam_pelaksanaan_alter_qcrecord_qc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 28, 15, 6, tzinfo=datetime.timezone.utc)),
        ),
    ]
