# Generated by Django 5.1.3 on 2025-01-14 00:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0057_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 1, 14, 7, 27, tzinfo=datetime.timezone.utc)),
        ),
    ]
