# Generated by Django 5.1.3 on 2025-01-25 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0058_qcrecord_date_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='shift',
            field=models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='P', max_length=15),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 1, 25, 22, 52, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='kel_sebelum',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='kelompok',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1', max_length=1),
        ),
    ]
