# Generated by Django 5.1.3 on 2024-12-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qcrecord',
            table='QC Records',
        ),
    ]
