# Generated by Django 5.1.3 on 2024-12-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_operator_qcrecord_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='NIP',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='NIP',
            field=models.CharField(default='000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.operator'),
        ),
    ]
