# Generated by Django 5.1.3 on 2024-12-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_alter_operator_nip_alter_qcrecord_nip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='NIP',
            field=models.CharField(max_length=18),
        ),
    ]
