# Generated by Django 5.1.3 on 2024-12-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_alter_qcrecord_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcrecord',
            name='NIP',
        ),
        migrations.RemoveField(
            model_name='qcrecord',
            name='name',
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.operator'),
        ),
    ]
