# Generated by Django 5.1.3 on 2024-12-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_remove_qcrecord_nip_remove_qcrecord_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='NIP',
            field=models.CharField(default='0', max_length=18),
        ),
    ]
