# Generated by Django 5.1.3 on 2024-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_qcrecord_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='qc_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
