# Generated by Django 5.1.3 on 2024-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0012_qcrecord_date_alter_qcrecord_qc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcrecord',
            name='date',
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='qc',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='qc_prev',
            field=models.TextField(default='0'),
        ),
    ]
