# Generated by Django 5.1.3 on 2024-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0014_qcrecord_jam_pelaksanaan_qcrecord_kelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='kelompok',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
    ]
