# Generated by Django 5.1.3 on 2024-12-18 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0032_remove_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 3, 27, tzinfo=datetime.timezone.utc)),
        ),
    ]
