# Generated by Django 5.1.3 on 2024-12-24 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0039_qcrecord_event_indonesia_qcrecord_event_luar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 24, 17, 35, tzinfo=datetime.timezone.utc)),
        ),
    ]
