# Generated by Django 5.1.3 on 2024-12-27 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0046_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='kel_sebelum',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 27, 14, 55, tzinfo=datetime.timezone.utc)),
        ),
    ]
