# Generated by Django 5.1.3 on 2024-12-28 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0047_qcrecord_kel_sebelum_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2024, 12, 28, 15, 5, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='qc_id',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
