# Generated by Django 5.1.3 on 2025-01-04 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0055_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 1, 4, 13, 51, tzinfo=datetime.timezone.utc)),
        ),
    ]
