# Generated by Django 5.1.3 on 2025-01-25 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0059_qcrecord_shift_alter_qcrecord_jam_pelaksanaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 1, 26, 0, 3, tzinfo=datetime.timezone.utc)),
        ),
    ]
