# Generated by Django 5.1.3 on 2025-01-28 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0061_alter_qcrecord_jam_pelaksanaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 1, 28, 10, 2, tzinfo=datetime.timezone.utc)),
        ),
    ]
