# Generated by Django 5.1.3 on 2025-02-02 22:53

import datetime
import qc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0063_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='date',
            field=models.DateField(default=qc.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 2, 3, 5, 53, tzinfo=datetime.timezone.utc)),
        ),
    ]
