# Generated by Django 5.1.2 on 2025-02-13 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0064_alter_qcrecord_date_alter_qcrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 2, 13, 9, 37, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='kel_sebelum',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='qcrecord',
            name='kelompok',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
    ]
