# Generated by Django 5.1.2 on 2025-02-13 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0065_alter_qcrecord_jam_pelaksanaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 2, 13, 10, 3, tzinfo=datetime.timezone.utc)),
        ),
    ]
