# Generated by Django 5.1.3 on 2025-02-22 06:27

import bast.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_kelompok_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BastRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=bast.models.get_default_date)),
                ('bast_id', models.CharField(default='0', max_length=17)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='Pagi', max_length=15)),
                ('kelompok', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('kel_berikut', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('events', models.TextField(default='0')),
                ('NIP', models.CharField(default='0', max_length=18)),
                ('event_indonesia', models.IntegerField(default=0)),
                ('event_luar', models.IntegerField(default=0)),
                ('event_dirasakan', models.IntegerField(default=0)),
                ('event_dikirim', models.IntegerField(default=0)),
                ('spv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
    ]
