# Generated by Django 5.1.3 on 2025-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bastrecordmodel',
            name='member',
            field=models.CharField(default='', max_length=300),
        ),
    ]
