# Generated by Django 5.1.3 on 2025-02-28 00:22

import bast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0002_bastrecordmodel_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bastrecordmodel',
            name='count_blanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='count_gaps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='count_spikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='poco_exp',
            field=models.DateField(default=bast.models.get_default_date),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='pulsa_poco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='pulsa_samsung',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastrecordmodel',
            name='samsung_exp',
            field=models.DateField(default=bast.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='bastrecordmodel',
            name='NIP',
            field=models.CharField(blank=True, default='0', max_length=18),
        ),
    ]
