# Generated by Django 5.1.3 on 2025-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0003_bastrecordmodel_count_blanks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bastrecordmodel',
            name='waktu_pelaksaan',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
