# Generated by Django 5.1.3 on 2025-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0004_bastrecordmodel_waktu_pelaksaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bastrecordmodel',
            name='waktu_pelaksaan',
            field=models.CharField(blank=True, choices=[('08:30 - 14:00 WIB', '08:30 - 14:00 WIB'), ('14:00 - 20:00 WIB', '14:00 - 20:00 WIB'), ('20:00 - 02:00 WIB', '20:00 - 02:00 WIB'), ('02:00 - 08:30 WIB', '02:00 - 08:30 WIB')], default='08:30 - 14:00 WIB', max_length=20, null=True),
        ),
    ]
