# Generated by Django 5.1.3 on 2025-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0005_alter_bastrecordmodel_waktu_pelaksaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bastrecordmodel',
            name='member',
            field=models.TextField(default='', max_length=300),
        ),
    ]
