# Generated by Django 5.1.3 on 2025-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0006_alter_bastrecordmodel_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bastrecordmodel',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bastrecordmodel',
            name='member',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
