# Generated by Django 5.1.3 on 2025-03-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0007_bastrecordmodel_notes_alter_bastrecordmodel_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bastrecordmodel',
            old_name='waktu_pelaksaan',
            new_name='waktu_pelaksanaan',
        ),
    ]
