# Generated by Django 5.1.3 on 2025-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0008_rename_waktu_pelaksaan_bastrecordmodel_waktu_pelaksanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bastrecordmodel',
            name='waktu_cs',
            field=models.CharField(default='00:00 WIB', max_length=20),
        ),
    ]
