# Generated by Django 5.1.3 on 2025-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0009_bastrecordmodel_waktu_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bastrecordmodel',
            name='waktu_cs',
            field=models.CharField(blank=True, default='00:00 WIB', max_length=20, null=True),
        ),
    ]
