# Generated by Django 5.1.3 on 2025-03-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bast', '0010_alter_bastrecordmodel_waktu_cs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bastrecordmodel',
            name='pulsa_samsung',
        ),
    ]
