# Generated by Django 5.1.3 on 2025-03-16 03:42

import datetime
import django.db.models.deletion
import qcfm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_kelompok_member_kelompok_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcFmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=qcfm.models.get_default_date)),
                ('qcfm_id', models.CharField(default='0', max_length=15)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam'), ('Dini Hari', 'Dini Hari')], default='P', max_length=15)),
                ('kelompok', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1)),
                ('jam_pelaksanaan', models.TimeField(default=datetime.datetime(2025, 3, 16, 10, 42, tzinfo=datetime.timezone.utc))),
                ('qcfm_prev', models.TextField(default='0')),
                ('qcfm', models.TextField(default='0')),
                ('NIP', models.CharField(default='0', max_length=18)),
                ('event_indonesia', models.IntegerField(default=0)),
                ('event_luar', models.IntegerField(default=0)),
                ('kel_sebelum', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
        ),
    ]
