# Generated by Django 5.1.3 on 2025-03-16 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcfmrecord',
            name='NIP',
            field=models.CharField(blank=True, default='0', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='qcfmrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 3, 16, 11, 23, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='qcfmrecord',
            name='qcfm_id',
            field=models.CharField(default='0', max_length=17),
        ),
    ]
