# Generated by Django 5.1.3 on 2025-03-16 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcfm', '0002_alter_qcfmrecord_nip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcfmrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 3, 16, 14, 21, tzinfo=datetime.timezone.utc)),
        ),
    ]
