# Generated by Django 5.1.3 on 2025-03-18 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcfm', '0003_alter_qcfmrecord_jam_pelaksanaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcfmrecord',
            name='event_indonesia',
        ),
        migrations.RemoveField(
            model_name='qcfmrecord',
            name='event_luar',
        ),
        migrations.AlterField(
            model_name='qcfmrecord',
            name='jam_pelaksanaan',
            field=models.TimeField(default=datetime.datetime(2025, 3, 18, 10, 30, tzinfo=datetime.timezone.utc)),
        ),
    ]
